In [1]:
import pandas as pd

In [2]:
df=pd.DataFrame({
    "Price":[100,200,300]
})
print(type(df["Price"].values))

<class 'numpy.ndarray'>


In [3]:
import numpy as np

In [18]:
salary=[1000,2000,3000]
# type(salary)
salary_array=np.array(salary)
# type(salary_array)
new_salary_array=salary_array+1
new_salary_array
salary_array.ndim
salary_array.shape
salary_array.size
print(salary_array[0])

1000


In [23]:
data=np.array([
    [10,1000],
    [20,2000],
    [30,3000],
    [40,1000],
    [50,2000],
    [60,3000]
])
data
data.ndim
data.shape
data.size
print(data[0,1])
print(data[0 :3])
print(data[:,1])#(row,column)

1000
[[  10 1000]
 [  20 2000]
 [  30 3000]]
[1000 2000 3000 1000 2000 3000]


In [21]:
price=np.array([10,10,30,40.5])
print(price.dtype)

float64


In [24]:
# numbers=[1,2,3,4,5]
# results=[]
# for num in numbers:
#     results.append(num*10)
# results



[10, 20, 30, 40, 50]

In [30]:
numbers=np.array([1,2,3,4,5])
results=numbers*10
print(results)
results>30
results[results>30]
results[(results>30)&(results<50)]

[10 20 30 40 50]


array([40])

In [31]:
pp=np.array([100,200,300])
qq=np.array([2,4,6])
pp*qq

array([ 200,  800, 1800])

In [36]:
arr=np.array([1,2,3,4,5,6])
arr.shape
arr.reshape(2,3)
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
arr2=np.array([
    [10,1000,3],
    [20,2000,5],
   
    ])
arr2.shape
# arr2.reshape(1,6)
arr2.reshape(-1)#-1 calculates automatically calculates
arr2.reshape(-1,2)

array([[  10, 1000],
       [   3,   20],
       [2000,    5]])