In [1]:
import pandas as pd
import numpy as np

In [8]:
df=pd.read_csv("datasets/daraz_dataset.csv")
df.head()
df.shape
df.dtypes
numeric_columns=[
"Age",
"Quantity",
"UnitPrice",
"DiscountPercent",
"TotalAmount",
"Rating"
]
for column in numeric_columns:
    df[column]=pd.to_numeric(df[column],errors="coerce")

# df.isnull().sum()
# df["Quantity"]=df["Quantity"].fillna(df["Quantity"].mean())
features=["Age","Quantity","UnitPrice","DiscountPercent"]
target=features=["TotalAmount"]
#Super features store garna X,target store garna y banauney
X=df[features]
y=df[target]

X=X.to_numpy()
y=y.to_numpy()
type(X)
type(y)
X.shape
X.ndim
X.dtype
X.nbytes
X[:,0]
(X[X[:,0]>30])
np.min(X[:,0])
age=np.array([10,20,30])
roll=np.array([1,2,3])
print(age)
print(roll)

[10 20 30]
[1 2 3]


In [13]:
# sdata=np.array([12,90])
# weights=np.array([10,2])
# prediction=np.dot(sdata,weights)
# prediction
sdata=np.array([
    [12,90],
    [14,80],
    [16,50]
               ])
weights=np.array([
    [10],
[2]
])
prediction=np.dot(sdata,weights)
prediction

array([[300],
       [300],
       [260]])